# Site settings
title: "Prakhar Sah"
description: "My online CV."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Prakhar Sah"
resume_title:                   "Doctoral Student | CS@VT"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "sprakhar@vt.edu"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       ""
resume_contact_address:         "220 Gilbert Street, Level 4, Room #4305, Blacksburg, VA 24060"

resume_header_contact_info:     "220 Gilbert Street, Blacksburg, VA 24060 | sprakhar [at] vt.edu"
display_header_contact_info:    "true"

resume_header_intro: "<p>With an experience of 3+ years in the areas of Computer Architecture, Embedded Systems
and Security, my research projects range from firmware level security to hardware/software
co-design. In particular, I am interested in evaluating and strengthening the security of
systems in resource-constrained and untrusted environments.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      false
resume_section_education:       true
resume_section_publications:    true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/prakhar-sah"
  resume_twitter_url:           "https://x.com/prakhar_sah_"
  # resume_dribbble_url:          ""
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/prakhar-sah"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "http://joelglovier.com"
  # resume_medium_url:            "https://medium.com/@jglovier"
  resume_gscholar_url:          "https://scholar.google.com/citations?hl=en&user=6prfRnoAAAAJ"
  resume_cv_url:                "my-cv.pdf"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
